{{- if .Values.prometheus.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "phoenix.fullname" . }}
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
    {{- with .Values.prometheus.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "phoenix.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.prometheus.podMonitor.interval | default "30s" }}
      {{- if .Values.prometheus.apiKey }}
      authorization:
        type: Bearer
        credentials:
          name: {{ include "phoenix.fullname" . }}
          key: metrics-api-key
      {{- end }}
{{- end }}