run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - prealloc
    - copyloopvar
    - nilerr
    - whitespace

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  errcheck:
    check-type-assertions: false
    check-blank: false
  goimports:
    local-prefixes: phoenix
  misspell:
    locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude-dirs:
    - web
    - charts
    - research
