# Uptime Phoenix Helm Chart
apiVersion: v2
name: uptime-phoenix
description: A self-hosted, K8s-native, minimal-dependency monitoring tool
type: application
version: 0.4.0
appVersion: "0.4.0"
dependencies:
  - name: valkey
    version: 0.11.0
    repository: https://valkey.io/valkey-helm/
    condition: valkey.enabled
annotations:
  artifacthub.io/license: MIT
keywords:
  - monitoring
  - uptime
  - health-check
  - kubernetes
home: https://github.com/fiztoz/uptime-phoenix
sources:
  - https://github.com/fiztoz/uptime-phoenix
maintainers:
  - name: Uptime Phoenix
    email: team@phoenix.dev
