apiVersion: v1
kind: Secret
metadata:
  name: {{ include "phoenix.fullname" . }}
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ include "phoenix.jwtSecret" . | b64enc | quote }}
  {{- if .Values.mariadb.enabled }}
  mariadb-root-password: {{ include "phoenix.dbPassword" . | b64enc | quote }}
  {{- end }}
  {{- if and .Values.redis.enabled (not .Values.redis.existingSecret) }}
  {{- $redisHost := default "redis-master" .Values.redis.host }}
  {{- $redisPort := int (default 6379 .Values.redis.port) }}
  {{- $redisAuth := "" }}
  {{- if .Values.redis.password }}{{- $redisAuth = printf ":%s@" .Values.redis.password }}{{- end }}
  redis-url: {{ printf "redis://%s%s:%d/0" $redisAuth $redisHost $redisPort | b64enc | quote }}
  {{- end }}
  {{- if and .Values.prometheus.podMonitor.enabled .Values.prometheus.apiKey }}
  metrics-api-key: {{ .Values.prometheus.apiKey | b64enc | quote }}
  {{- end }}
  {{- if and .Values.oidc.enabled .Values.oidc.clientSecret (not .Values.oidc.existingSecret) }}
  oidc-client-secret: {{ .Values.oidc.clientSecret | b64enc | quote }}
  {{- end }}
