ALTER TABLE heartbeat_1m ADD COLUMN ping_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE heartbeat_1h ADD COLUMN ping_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE heartbeat_1d ADD COLUMN ping_count INTEGER NOT NULL DEFAULT 0;
