CREATE TEMPORARY TABLE probe_history_downgrade_guard (n INTEGER CHECK (n = 0));
INSERT INTO probe_history_downgrade_guard SELECT COUNT(*) FROM heartbeat_1m WHERE history_managed = TRUE;
INSERT INTO probe_history_downgrade_guard SELECT COUNT(*) FROM heartbeat_1h WHERE history_managed = TRUE;
INSERT INTO probe_history_downgrade_guard SELECT COUNT(*) FROM heartbeat_1d WHERE history_managed = TRUE;
INSERT INTO probe_history_downgrade_guard SELECT COUNT(*) FROM probe_history_ranges;
DROP TABLE probe_history_downgrade_guard;
DROP TABLE probe_history_ranges;
DROP INDEX idx_probe_observations_history_time ON probe_observations;
DROP INDEX idx_probe_observations_history_seed ON probe_observations;
ALTER TABLE heartbeat_1m DROP COLUMN up_us;
ALTER TABLE heartbeat_1m DROP COLUMN down_us;
ALTER TABLE heartbeat_1m DROP COLUMN pending_us;
ALTER TABLE heartbeat_1m DROP COLUMN unknown_us;
ALTER TABLE heartbeat_1m DROP COLUMN maintenance_us;
ALTER TABLE heartbeat_1m DROP COLUMN paused_us;
ALTER TABLE heartbeat_1m DROP COLUMN history_managed;
ALTER TABLE heartbeat_1h DROP COLUMN up_us;
ALTER TABLE heartbeat_1h DROP COLUMN down_us;
ALTER TABLE heartbeat_1h DROP COLUMN pending_us;
ALTER TABLE heartbeat_1h DROP COLUMN unknown_us;
ALTER TABLE heartbeat_1h DROP COLUMN maintenance_us;
ALTER TABLE heartbeat_1h DROP COLUMN paused_us;
ALTER TABLE heartbeat_1h DROP COLUMN history_managed;
ALTER TABLE heartbeat_1d DROP COLUMN up_us;
ALTER TABLE heartbeat_1d DROP COLUMN down_us;
ALTER TABLE heartbeat_1d DROP COLUMN pending_us;
ALTER TABLE heartbeat_1d DROP COLUMN unknown_us;
ALTER TABLE heartbeat_1d DROP COLUMN maintenance_us;
ALTER TABLE heartbeat_1d DROP COLUMN paused_us;
ALTER TABLE heartbeat_1d DROP COLUMN history_managed;
ALTER TABLE probe_dirty_buckets DROP COLUMN revision;
